### ISSUE TITLE
Claude V2

### ISSUE THREAD

**Issue by aaweb** [themaximal1st/llm.js#2]
Dear Maximal1st team,

Awesome repo! Been using the component for a few weeks and its amazing. I wonder why this repo is not much much more popular?

I was wondering if there are plans to add Claude V2. I tried using it by just adjusting the model string but always receive an error. Thanks for the update. If this is not actively developed, it's OK as well, but please let me know as I'd have to look for another solution (even though I love the elegance of this one)

Andy

**Comment by aaweb** [comment]
Edit: I actually meant to ask this on the ai.js package.

**Comment by themaximal1st** [comment]
Hello sorry for the delay, Claude v2 should be supported in both LLM.js and AI.js!
